/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Gender = IDL.Variant({
  'other' : IDL.Text,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const MeridianReading = IDL.Record({
  'qi' : IDL.Int,
  'meridian' : IDL.Text,
  'vata' : IDL.Int,
  'acidBase' : IDL.Int,
  'pitta' : IDL.Int,
  'kapha' : IDL.Int,
});
export const Patient = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'gender' : Gender,
});
export const Practitioner = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'icianId' : IDL.Text,
});
export const Session = IDL.Record({
  'id' : IDL.Nat,
  'modalitiesUsed' : IDL.Vec(IDL.Text),
  'patientId' : IDL.Nat,
  'date' : IDL.Text,
  'meridianReadings' : IDL.Vec(MeridianReading),
});

export const idlService = IDL.Service({
  'addPatient' : IDL.Func([IDL.Text, IDL.Nat, Gender, IDL.Text], [IDL.Nat], []),
  'createSession' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(MeridianReading)],
      [IDL.Nat],
      [],
    ),
  'getPatient' : IDL.Func([IDL.Nat], [Patient], ['query']),
  'getPractitioner' : IDL.Func([IDL.Text], [Practitioner], ['query']),
  'getSession' : IDL.Func([IDL.Nat], [Session], ['query']),
  'getSessionsByPatient' : IDL.Func([IDL.Nat], [IDL.Vec(Session)], ['query']),
  'getTodaysSessions' : IDL.Func([IDL.Text], [IDL.Vec(Session)], ['query']),
  'getTotalPatients' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalSessions' : IDL.Func([], [IDL.Nat], ['query']),
  'listPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'listSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'savePractitioner' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'searchPatients' : IDL.Func([IDL.Text], [IDL.Vec(Patient)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Gender = IDL.Variant({
    'other' : IDL.Text,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const MeridianReading = IDL.Record({
    'qi' : IDL.Int,
    'meridian' : IDL.Text,
    'vata' : IDL.Int,
    'acidBase' : IDL.Int,
    'pitta' : IDL.Int,
    'kapha' : IDL.Int,
  });
  const Patient = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'gender' : Gender,
  });
  const Practitioner = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'icianId' : IDL.Text,
  });
  const Session = IDL.Record({
    'id' : IDL.Nat,
    'modalitiesUsed' : IDL.Vec(IDL.Text),
    'patientId' : IDL.Nat,
    'date' : IDL.Text,
    'meridianReadings' : IDL.Vec(MeridianReading),
  });
  
  return IDL.Service({
    'addPatient' : IDL.Func(
        [IDL.Text, IDL.Nat, Gender, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createSession' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(MeridianReading)],
        [IDL.Nat],
        [],
      ),
    'getPatient' : IDL.Func([IDL.Nat], [Patient], ['query']),
    'getPractitioner' : IDL.Func([IDL.Text], [Practitioner], ['query']),
    'getSession' : IDL.Func([IDL.Nat], [Session], ['query']),
    'getSessionsByPatient' : IDL.Func([IDL.Nat], [IDL.Vec(Session)], ['query']),
    'getTodaysSessions' : IDL.Func([IDL.Text], [IDL.Vec(Session)], ['query']),
    'getTotalPatients' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalSessions' : IDL.Func([], [IDL.Nat], ['query']),
    'listPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'listSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'savePractitioner' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'searchPatients' : IDL.Func([IDL.Text], [IDL.Vec(Patient)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };