/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Gender = { 'other' : string } |
  { 'female' : null } |
  { 'male' : null };
export interface MeridianReading {
  'qi' : bigint,
  'meridian' : string,
  'vata' : bigint,
  'acidBase' : bigint,
  'pitta' : bigint,
  'kapha' : bigint,
}
export interface Patient {
  'id' : bigint,
  'age' : bigint,
  'contact' : string,
  'name' : string,
  'gender' : Gender,
}
export interface Practitioner {
  'name' : string,
  'role' : string,
  'icianId' : string,
}
export interface Session {
  'id' : bigint,
  'modalitiesUsed' : Array<string>,
  'patientId' : bigint,
  'date' : string,
  'meridianReadings' : Array<MeridianReading>,
}
export interface _SERVICE {
  'addPatient' : ActorMethod<[string, bigint, Gender, string], bigint>,
  'createSession' : ActorMethod<
    [bigint, string, Array<string>, Array<MeridianReading>],
    bigint
  >,
  'getPatient' : ActorMethod<[bigint], Patient>,
  'getPractitioner' : ActorMethod<[string], Practitioner>,
  'getSession' : ActorMethod<[bigint], Session>,
  'getSessionsByPatient' : ActorMethod<[bigint], Array<Session>>,
  'getTodaysSessions' : ActorMethod<[string], Array<Session>>,
  'getTotalPatients' : ActorMethod<[], bigint>,
  'getTotalSessions' : ActorMethod<[], bigint>,
  'listPatients' : ActorMethod<[], Array<Patient>>,
  'listSessions' : ActorMethod<[], Array<Session>>,
  'savePractitioner' : ActorMethod<[string, string, string], undefined>,
  'searchPatients' : ActorMethod<[string], Array<Patient>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];