/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Session {
    id: bigint;
    modalitiesUsed: Array<string>;
    patientId: bigint;
    date: string;
    meridianReadings: Array<MeridianReading>;
}
export interface Practitioner {
    name: string;
    role: string;
    icianId: string;
}
export type Gender = {
    __kind__: "other";
    other: string;
} | {
    __kind__: "female";
    female: null;
} | {
    __kind__: "male";
    male: null;
};
export interface Patient {
    id: bigint;
    age: bigint;
    contact: string;
    name: string;
    gender: Gender;
}
export interface MeridianReading {
    qi: bigint;
    meridian: string;
    vata: bigint;
    acidBase: bigint;
    pitta: bigint;
    kapha: bigint;
}
export interface backendInterface {
    addPatient(name: string, age: bigint, gender: Gender, contact: string): Promise<bigint>;
    createSession(patientId: bigint, date: string, modalities: Array<string>, readings: Array<MeridianReading>): Promise<bigint>;
    getPatient(id: bigint): Promise<Patient>;
    getPractitioner(id: string): Promise<Practitioner>;
    getSession(id: bigint): Promise<Session>;
    getSessionsByPatient(patientId: bigint): Promise<Array<Session>>;
    getTodaysSessions(date: string): Promise<Array<Session>>;
    getTotalPatients(): Promise<bigint>;
    getTotalSessions(): Promise<bigint>;
    listPatients(): Promise<Array<Patient>>;
    listSessions(): Promise<Array<Session>>;
    savePractitioner(id: string, name: string, role: string): Promise<void>;
    searchPatients(searchText: string): Promise<Array<Patient>>;
}
import type { Gender as _Gender, Patient as _Patient } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addPatient(arg0: string, arg1: bigint, arg2: Gender, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPatient(arg0, arg1, to_candid_Gender_n1(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPatient(arg0, arg1, to_candid_Gender_n1(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async createSession(arg0: bigint, arg1: string, arg2: Array<string>, arg3: Array<MeridianReading>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getPatient(arg0: bigint): Promise<Patient> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatient(arg0);
                return from_candid_Patient_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatient(arg0);
            return from_candid_Patient_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPractitioner(arg0: string): Promise<Practitioner> {
        if (this.processError) {
            try {
                const result = await this.actor.getPractitioner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPractitioner(arg0);
            return result;
        }
    }
    async getSession(arg0: bigint): Promise<Session> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return result;
        }
    }
    async getSessionsByPatient(arg0: bigint): Promise<Array<Session>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionsByPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionsByPatient(arg0);
            return result;
        }
    }
    async getTodaysSessions(arg0: string): Promise<Array<Session>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodaysSessions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodaysSessions(arg0);
            return result;
        }
    }
    async getTotalPatients(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalPatients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalPatients();
            return result;
        }
    }
    async getTotalSessions(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalSessions();
            return result;
        }
    }
    async listPatients(): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPatients();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPatients();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSessions(): Promise<Array<Session>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSessions();
            return result;
        }
    }
    async savePractitioner(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePractitioner(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePractitioner(arg0, arg1, arg2);
            return result;
        }
    }
    async searchPatients(arg0: string): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPatients(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPatients(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Gender_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Patient_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Patient): Patient {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    age: bigint;
    contact: string;
    name: string;
    gender: _Gender;
}): {
    id: bigint;
    age: bigint;
    contact: string;
    name: string;
    gender: Gender;
} {
    return {
        id: value.id,
        age: value.age,
        contact: value.contact,
        name: value.name,
        gender: from_candid_Gender_n5(_uploadFile, _downloadFile, value.gender)
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: string;
} | {
    female: null;
} | {
    male: null;
}): {
    __kind__: "other";
    other: string;
} | {
    __kind__: "female";
    female: null;
} | {
    __kind__: "male";
    male: null;
} {
    return "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "female" in value ? {
        __kind__: "female",
        female: value.female
    } : "male" in value ? {
        __kind__: "male",
        male: value.male
    } : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Patient>): Array<Patient> {
    return value.map((x)=>from_candid_Patient_n3(_uploadFile, _downloadFile, x));
}
function to_candid_Gender_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "other";
    other: string;
} | {
    __kind__: "female";
    female: null;
} | {
    __kind__: "male";
    male: null;
}): {
    other: string;
} | {
    female: null;
} | {
    male: null;
} {
    return value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "female" ? {
        female: value.female
    } : value.__kind__ === "male" ? {
        male: value.male
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
